# =============================================================================
# Title: Likely Causal Effects of Circulating Hormones on Puberty Timing:
#        a Mendelian Randomisation Study
# Description: Code to prepare data for Mendelian Randomisation. 
# Author: Lena Kaisinger
# =============================================================================

# Dependencies

# install.packages("tidyverse")
# install.packages("remotes")
# remotes::install_github("MRCIEU/TwoSampleMR")
# remotes::install_github("MRCIEU/MRInstruments")

library(TwoSampleMR)
library(MRInstruments)
library(tidyverse)

# Set working directory
setwd("/your/working/directory")

# ---------------------------------------------------------------------------
# Format GWAS summary statistics
# ---------------------------------------------------------------------------
# Run this step separately for each exposure, outcome, and covariate
# Column names/indices will differ across GWAS — update accordingly
# Files are generated by looking up list of independent signals in the
# relevant GWAS files using SNP and CHR/POS using a grep command

raw_data <- read_tsv("/your/file/path/unformatted_data", col_names = FALSE)

formatted_data <- raw_data %>%
  transmute(
    SNP           = X1,
    beta          = X2,
    se            = X3,
    effect_allele = X4,
    other_allele  = X5,
    eaf           = X6,
    pval          = X7,
    samplesize    = 20000,        
    name          = "variable_name"
  )

write_tsv(formatted_data, file = "/your/file/path/formatted_data")

# ---------------------------------------------------------------------------
# Add proxy SNPs (skip if not needed)
# ---------------------------------------------------------------------------
# The proxy file contains columns from both the original GWAS and the GWAS with the missing SNPs for which the proxies are needed
# Run this step separately for each exposure, outcome and covariate that requires proxies
# NB: Column names will differ across GWAS — update accordingly

proxies_raw <- read_tsv("/your/file/path/proxies.txt", col_names = TRUE)

proxies_formatted <- proxies_raw %>%
  transmute(
    SNP           = Proxy,
    beta          = BETA,
    se            = SE,
    effect_allele = ALLELE1,
    other_allele  = ALLELE0,
    eaf           = A1FREQ,
    pval          = P,
    samplesize    = 20000,        
    name          = "variable_name"
  )

# Append proxies to formatted data and save
formatted_data_with_proxies <- read_tsv("/your/file/path/formatted_data",
                                        col_names = TRUE) %>%
  bind_rows(proxies_formatted)

write_tsv(formatted_data_with_proxies,
          file = "/your/file/path/formatted_data_with_proxies")

# ---------------------------------------------------------------------------
# Positive betas for exposure (skip for the others)
# ---------------------------------------------------------------------------
# Where beta is negative, swap effect and other allele and flip eaf to 1 - eaf
# This ensures consistent directionality across exposure SNPs

formatted_data <- formatted_data %>%
  mutate(
    flip          = beta < 0,
    temp          = effect_allele,
    effect_allele = if_else(flip, other_allele, effect_allele),
    other_allele  = if_else(flip, temp, other_allele),
    eaf           = if_else(flip, 1 - eaf, eaf),
    beta          = abs(beta)
  ) %>%
  select(-flip, -temp)

write_tsv(formatted_data, file = "/your/file/path/formatted_data")

# ---------------------------------------------------------------------------
# Harmonise exposure and outcome data
# ---------------------------------------------------------------------------
# Data needs to be in .txt format
# Effect estimates for exposure need to be positive!

exposure <- read_exposure_data(
  "/your/exposure/formatted_exposure_with_proxies",
  clump = FALSE,
  sep = "\t",
  snp_col = "SNP",
  phenotype_col = "name",
  beta_col = "beta",
  se_col = "se",
  eaf_col = "eaf",
  effect_allele_col = "effect_allele",
  other_allele_col = "other_allele",
  pval_col = "pval",
  samplesize_col = "samplesize",
  min_pval = 5e-324, # R doesn't like smaller values
  log_pval = FALSE
)

outcome <- read_outcome_data(
  "/your/exposure/formatted_outcome_with_proxies",
  snps = NULL,
  sep = "\t",
  phenotype_col = "name",
  snp_col = "SNP",
  beta_col = "beta",
  se_col = "se",
  eaf_col = "eaf",
  effect_allele_col = "effect_allele",
  other_allele_col = "other_allele",
  pval_col = "pval",
  samplesize_col = "samplesize",
  min_pval = 5e-324,
  log_pval = FALSE
)

# use action = 1 to keep all alleles 
formatted_mr_data <- harmonise_data(exposure, outcome, action=1)

# ---------------------------------------------------------------------------
# Steiger filtering
# ---------------------------------------------------------------------------

# NB! All SNPs are kept and only flagged - filtering is happening later
steiger <- steiger_filtering(formatted_mr_data)
write.csv(steiger, file="/your/file/path/exposure_outcome_harmonised_steiger.csv", row.names = FALSE)

# ---------------------------------------------------------------------------
# Format data for multivariable MR
# ---------------------------------------------------------------------------
# Merges the primary harmonised dataset with a covariate dataset
# The confounder betas are renamed to beta.confounder/se.confounder
# and joined to the primary data by SNP
# To add further covariates, repeat the pattern below with beta.confounder2 etc.

# Primary harmonised MR data
data_primary <- read_csv("/your/file/path/primary_harmonised.csv")

# Confounder data — extract and rename relevant columns
data_confounder <- read_csv("/your/file/path/confounder_harmonised.csv") %>%
  transmute(
    SNP            = SNP,
    beta.confounder = beta.outcome,
    se.confounder   = se.outcome
  )

# Merge and save
data_mvmr <- left_join(data_primary, data_confounder, by = "SNP")
write.csv(data_mvmr, file = "/your/file/path/mvmr_formatted.csv", row.names = FALSE)
